//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdemMedina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestDetail
    {
        public int Id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> cardTypeID { get; set; }
        public Nullable<int> requestID { get; set; }
    
        public virtual CardType CardType { get; set; }
        public virtual Request Request { get; set; }
    }
}
